# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frm_title = QtWidgets.QFrame(parent=self.centralwidget)
        self.frm_title.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_title.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_title.setObjectName("frm_title")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frm_title)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_title_icon = QtWidgets.QLabel(parent=self.frm_title)
        self.lbl_title_icon.setObjectName("lbl_title_icon")
        self.horizontalLayout.addWidget(self.lbl_title_icon)
        self.lbl_title = QtWidgets.QLabel(parent=self.frm_title)
        self.lbl_title.setObjectName("lbl_title")
        self.horizontalLayout.addWidget(self.lbl_title)
        self.pushButton = QtWidgets.QPushButton(parent=self.frm_title)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout.addWidget(self.frm_title, 0, 0, 1, 2)
        self.stck_wdgt_main = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stck_wdgt_main.setObjectName("stck_wdgt_main")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stck_wdgt_main.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stck_wdgt_main.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stck_wdgt_main, 0, 2, 2, 1)
        self.lst_wdgt_menu_icons_only = QtWidgets.QListWidget(parent=self.centralwidget)
        self.lst_wdgt_menu_icons_only.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lst_wdgt_menu_icons_only.setObjectName("lst_wdgt_menu_icons_only")
        self.gridLayout.addWidget(self.lst_wdgt_menu_icons_only, 1, 0, 1, 1)
        self.lst_wdgt_menu = QtWidgets.QListWidget(parent=self.centralwidget)
        self.lst_wdgt_menu.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lst_wdgt_menu.setObjectName("lst_wdgt_menu")
        self.gridLayout.addWidget(self.lst_wdgt_menu, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 42))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_title_icon.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_title.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
